### PR TITLE
Update README badge for GH Actions

### PR DESCRIPTION
**Pull request by jaimergp**
I forgot to add the badge to the README in #554 😬

### CODE REVIEW

**Comment by jaimergp** [comment]
Why is Travis still showing up? Do we have to disable the repo in their settings page?

**Comment by jaimergp** [comment]
And... why does it say [this link](https://github.com/openforcefield/openforcefield/workflows/CI/badge.svg) is broken?

**Comment by j-wags** [comment]
Good find. I've changed the branch protection settings for the `openforcefield/openforcefield` repo, changing the GHA statuses to be "required", and de-selecting the travis status. 

Travis may continue pushing failing statuses, and I don't see a way to hide them from the GitHub side, so I probably need to disable them on travis-ci.org. However I've had trouble with admin access on there the last few days. Will delete cookies _again_ and try to get into that.

**Comment by j-wags** [comment]
Ok, I've disabled Travis builds. That should remove the status checks.

**Comment by jaimergp** [comment]
I think we are still seeing the badge link error:

```
FAILED openforcefield/tests/test_examples.py::test_readme_links[https://github.com/openforcefield/openforcefield/workflows/CI/badge.svg]
```

I'll re-run to see if it was related to the GH shortages some hours ago.

**Comment by mattwthompson** [comment]
Those same test seems to still be the cause of these "failures" although I can open the link just fine in my browser

**Comment by jaimergp** [comment]
Wow Jeff, _that_ was the problem? Header order?! Phew, I am glad you caught that! I would have never guessed it. This can be merged now!

**Comment by j-wags** [comment]
I had to do a LOT of local experimentation and website inspection to figure that out. I''m glad I'm not a web developer!

**Pull request merged**
