### PR TITLE
Fix #163: Make ForceField look automatically in data/forcefield

### LINKED ISSUE #163: Make ForceField look automatically in data/forcefield directory instead of data/
Currently when we need to prepend `forcefield/` to all offxml files defined in the repo
```
forcefield = ForceField('forcefield/Frosst_AlkEthOH_parmAtFrosst.offxml')
```
Should we make `ForceField` look automatically in `data/forcefield/` in [this snippet](https://github.com/openforcefield/openforcefield/blob/77e66993daacdfba61d89888cca82223452b621b/openforcefield/typing/engines/smirnoff/forcefield.py#L556) instead of just `data/` and make the call a little simpler?
```
forcefield = ForceField('Frosst_AlkEthOH_parmAtFrosst.offxml')
```
Or is there a reason I don't see to avoid this?

### PR DESCRIPTION
**Pull request by andrrizzi**
This implements #163 .

I think I got all the `ForceField` constructors. I found a few inconsistencies every now and then.

### CODE REVIEW

**Comment by davidlmobley** [comment]
That would be a good idea.

**Comment by andrrizzi** [comment]
I can work on this if it's considered high-priority.

**Comment by jchodera** [comment]
We can implement this at the same time as we update the https://github.com/openforcefield/smirnoff99frosst repo to install into the entry point.

**Comment by andrrizzi** [comment]
Sounds good. I think you already captured this in #117.

**Pull request merged**
