### PR TITLE
Remove generics, add hydrogen radii, rename ffxml files

### PR DESCRIPTION
**Pull request by davidlmobley**
This PR will:
- [x] Remove generic atoms matching any element from smirnoff99Frosst so exceptions are raised if parameters are assigned to a molecule which contains an element we don't cover (osmium, anyone?), per #75 and https://github.com/openforcefield/smirnoff99Frosst/issues/72
- [x] Move generic parameters to a separate, optional `generics.ffxml` file per #75 
- [x] Rename `.ffxml` files to `.offxml` files to reduce confusion between these and "normal" OpenMM ffxml files per #92 
- [x] Add hydroxyl LJ parameters (as validated in the `SMIRNOFF_paper_code` repo), but I haven't brought them in to this main repo yet) as per https://github.com/openforcefield/smirnoff99Frosst/issues/61
- [x] Update example/testing scripts and Jupyter notebooks to load offxml rather than ffxml files (ugh). (Update: Atom can do global search and replace across a whole project, even inside Jupyter notebooks. Not so much ugh.)

So far I have:
- Migrated the ffxml files in `convert_frosst` to `offxml`
- Removed generics in the smirnoffishFrcmod files in `convert_frosst`
- Split out a separate `generics.ffxml` file in `convert_frosst`, but still needs slightly less crazy parameters (@bannanc take a quick stab at this?) and then I'll copy it to the data directory
- Add hydroxyl LJ parameters and documentation of how selected
- Regenerate `.offxml` files in `convert_frosst` and propagate to data directory

plus doing the boxes checked above.

### CODE REVIEW

**Comment by bannanc** [comment]
@davidlmobley 
I think these parameters for generics make the most sense:
```
[*:1]     1.9    0.1

[*:1]~[*:2]    310.0    1.5

[*:1]~[*:2]~[*:3]    50.    120.

[*:1]~[*:2]~[*:3]~[*:4]    1     0.0    0.0    2
```
Long story short, I think they would be reasonable guesses for most boron compounds and thats one of the main elements we know would get generic parameters. I added that logic to issue #75 and tagged Chris to make sure he agrees.

**Comment by davidlmobley** [comment]
Thanks, @bannanc .

**Comment by davidlmobley** [comment]
@bannanc - I think this is ready for review, but I'm going to try to fix the tests (which are failing for other reasons) in a separate PR.

**Comment by davidlmobley** [comment]
@bannanc - this seems to be ready for review. (Oddly, the py35 test is marked as failing (though the other two pass) but I'm not actually seeing anything wrong with it.)

**Comment by davidlmobley** [comment]
Agreed, yup, was just waiting for this one to be reviewed. I'll do that now. Thanks!

**Comment by bannanc** [comment]
@davidlmobley I can't force merge without the tests passing, can you do it?

**Pull request merged**
