### PR TITLE
Use frappuccino to check for API changes

### PR DESCRIPTION
**Pull request by mattwthompson**
https://pypi.org/project/frappuccino/

- [ ] Tag issue being addressed
- [ ] Add [tests](https://github.com/openforcefield/openforcefield/tree/master/openforcefield/tests)
- [ ] Update docstrings/[documentation](https://github.com/openforcefield/openforcefield/tree/master/docs), if applicable
- [ ] Update [changelog](https://github.com/openforcefield/openforcefield/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Comment by mattwthompson** [comment]
This package doesn't report exit status (yet) but the gist of it is accessible in the log (` Compare API of released and development versions`)

For example, right now the API changes are 

```
2020-07-11T16:28:20.1005785Z The following items are new:
2020-07-11T16:28:20.1006013Z     + openforcefield.utils.toolkits.inspect
2020-07-11T16:28:20.1006251Z     + openforcefield.typing.engines.smirnoff.parameters.DuplicateParameterError
2020-07-11T16:28:20.1006523Z     + openforcefield.utils.toolkits.ToolkitRegistry.deregister_toolkit(self, toolkit_wrapper)
2020-07-11T16:28:20.1006689Z 
2020-07-11T16:28:20.1006878Z The following signatures differ between versions:
2020-07-11T16:28:20.1007017Z 
2020-07-11T16:28:20.1007679Z     - openforcefield.typing.engines.smirnoff.parameters.ParameterHandler.add_parameter(self, parameter_kwargs)
2020-07-11T16:28:20.1008926Z     + openforcefield.typing.engines.smirnoff.parameters.ParameterHandler.add_parameter(self, parameter_kwargs='None', parameter='None', after='None', before='None')

```

And you can also grab different versions, i.e. here's the mess of changes between 0.6.0 and 0.7.0: https://gist.github.com/mattwthompson/b852e5b2748db27ca119bd0035010dcd

**Comment by jchodera** [comment]
Wow, this is awesome! Would it be worth adding this to the cookiecutter?

**Comment by mattwthompson** [comment]
It's more or less a personal project and maybe not mature enough right now to roll out with the cookiecutter, by default, in my opinion. It could be valuable as option for people who do care about API changes - probably opt-in since it would be annoying for a newer developer being yelled at by CI while they're rapidly changing the API of a fresh project. I opened it here since the toolkit values API stability (or at least would benefit from detailed information about changes) whereas it seems like most other projects in the community don't value it so much (outside of a few pillars, most are 0.x with an ~experimental API)

**Comment by mattwthompson** [comment]
Closing this in favor of housing it in https://github.com/openforcefield/status  later if useful in the release process.

**Pull request closed without merging**
