### PR TITLE
Removed check for all partial charges zero after assignment by quacpac

### PR DESCRIPTION
**Pull request by dotsdl**
Addresses #381.

We check for `quacpac` failure earlier, and we need to tolerate cases where the partial charges are legitimately all zero, such as for `N#N`.

The following now works without error:

```python
from openforcefield.topology import Molecule, Topology
from openforcefield.typing.engines.smirnoff import ForceField

molecule = Molecule.from_smiles('N#N')
topology = Topology.from_molecules([molecule])

force_field = ForceField('test_forcefields/smirnoff99Frosst.offxml')

system = force_field.create_openmm_system(topology)
system
```
And we can see that we get zero partial charges on all atoms as expected for this molecule:
```python
from openforcefield.topology import Molecule, Topology
from openforcefield.typing.engines.smirnoff import ForceField

molecule = Molecule.from_smiles('N#N')
topology = Topology.from_molecules([molecule])

molecule.generate_conformers()
molecule.compute_partial_charges_am1bcc()

molecule.partial_charges
````
yields:
```
Quantity(value=array([0., 0.]), unit=elementary charge)
```

- [x] Tag issue being addressed
- [x] Add [tests](https://github.com/openforcefield/openforcefield/tree/master/openforcefield/tests)
- [x] Update docstrings/[documentation](https://github.com/openforcefield/openforcefield/tree/master/docs), if applicable
- [x] Update [changelog](https://github.com/openforcefield/openforcefield/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Comment by dotsdl** [comment]
Thanks @mattwthompson!

I'm waiting for a response on [this question](https://github.com/openforcefield/openforcefield/issues/381#issuecomment-612158980). I do wonder if there are any cases where `quacpac_status` is `True` but charge assignment actually failed. If we have no reason to be concerned there, then we can proceed with this PR.

For tests, do we have any nontrivial example molecules that AM1BCC fails to parameterize, bonus points if they are known to have all zero partial charges? That last part may be overkill. I do know that say, a lithium ion will trigger failure of `quacpac`.

**Comment by davidlmobley** [comment]
I've never seen a case where quacpac returned True but charge assignment failed. One benefit of commercial code is that this type of thing tends to be well-behaved and problems will be dealt with severely.

However:
> For tests, do we have any nontrivial example molecules that AM1BCC fails to parameterize, bonus points if they are known to have all zero partial charges? That last part may be overkill. I do know that say, a lithium ion will trigger failure of quacpac.

I do not think we have any molecules that AM1BCC fails to parameterize. So far, except for the case of eg monatomic ions and metals, this seems to be a good "chemistry sanity check"; I am not currently aware of any cases of "well formed" molecules where the OpenEye AM1BCC fails. It does fail on some protonation states/tautomers we've occasionally enumerated but those tend to be "obviously wrong" ones. In other words, all the failures I've examined so far (and I've looked at a ton of them) have seemed to be cases of it filtering out bad chemistry.

**Comment by davidlmobley** [comment]
(Let me know if you want me to pull some of these for you; I could dig some up from my notes somewhere.)

**Comment by dotsdl** [comment]
Thanks @davidlmobley! I think that's more than satisfactory an explanation for us to proceed. I don't see the need for an explicit unit test here, as this runtime check we are removing appears both unnecessary and unreliable.

I'll add a changelog entry, and that should be all that's needed for this. @mattwthompson are you satisfied with this approach?

**Comment by mattwthompson** [comment]
Yes, I think this should be good to go; if a user would have to intentionally try very hard to break AM1BCC, that seems like something we don't need to worry about now.

**Comment by dotsdl** [comment]
Great! Thanks @mattwthompson! Merging!

**Pull request merged**
