### PR TITLE
Store IOError message from attribute, not str method

### PR DESCRIPTION
**Pull request by mattwthompson**
#629 
- [x] Tag issue being addressed
- [x] Add [tests](https://github.com/openforcefield/openforcefield/tree/master/openforcefield/tests)
- [ ] Update docstrings/[documentation](https://github.com/openforcefield/openforcefield/tree/master/docs), if applicable
- [ ] Update [changelog](https://github.com/openforcefield/openforcefield/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Comment by mattwthompson** [comment]
How it looks (compare to issue):

```python3
(openff-dev) [openforcefield] ipython                                                                                     bugfix-ff-string-parse
Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:33:30)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]:
   ...: from openforcefield.typing.engines.smirnoff.forcefield import ForceField
   ...: force_field = ForceField("1234")

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-3f7d2c9306e4> in <module>
      1 from openforcefield.typing.engines.smirnoff.forcefield import ForceField
----> 2 force_field = ForceField("1234")

~/software/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py in __init__(self, parameter_handler_classes, parameter_io_handler_classes, disable_version_check, allow_cosmetic_attributes, load_plugins, *sources)
    303
    304         # Parse all sources containing SMIRNOFF parameter definitions
--> 305         self.parse_sources(sources, allow_cosmetic_attributes=allow_cosmetic_attributes)
    306
    307     def _initialize(self):

~/software/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py in parse_sources(self, sources, allow_cosmetic_attributes)
    768         # TODO: If a non-first source fails here, the forcefield might be partially modified
    769         for source in sources:
--> 770             smirnoff_data = self.parse_smirnoff_from_source(source)
    771             self._load_smirnoff_data(smirnoff_data,
    772                                      allow_cosmetic_attributes=allow_cosmetic_attributes)

~/software/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py in parse_smirnoff_from_source(self, source)
    989         msg += f"Valid formats are: {valid_formats}\n"
    990         msg += f"Parsing failed with the following error:\n{exception_msg}\n"
--> 991         raise IOError(msg)
    992
    993

OSError: Source 1234 could not be read. If this is a file, ensure that the path is correct.
If the file is present, ensure it is in a known SMIRNOFF encoding.
Valid formats are: ['XML']
Parsing failed with the following error:
syntax error: line 1, column 0

**Comment by mattwthompson** [comment]
Seeing as this behavior was [missed in the unit tests](https://codecov.io/gh/openforcefield/openforcefield/src/131d86c7cacc3bbd98d10114a3b326ec1d7db9f9/openforcefield/typing/engines/smirnoff/forcefield.py) I've added a simple unit test for the case of a file not existing. I poked around in a few reference OFFXML files and could not find one that triggers the `ParseError` catch a few lines earlier.

**Comment by SimonBoothroyd** [comment]
(see also https://github.com/openforcefield/openforcefield/issues/629#issuecomment-650455653)

**Comment by mattwthompson** [comment]
It may be worth nuking 29384a935a896f8f1b1d9271d6b2a2607fc61d76 from the history, but a4b8daf fixes the error you found in how `ParseError` is being raids

**Pull request merged**
