### PR TITLE
Fix `!1` typo in smirnoff99Frosst

### PR DESCRIPTION
**Pull request by bannanc**
As discussed in issue #247 I fixed `!1` to `!#1` in parameter `t56`. 
In doing this I followed the same procedure I usually would, I changed the relevant files in the `utilities/convert_frosst/` folder for the posterity of the forcefield and then I changed `openforcefield/data/forcefield/smirnoff99frosst.offxml`. 

In this process I noticed that the `offxml` file in the `convert_frosst` folder and the one in the smirnoff99Frosst repo have smirnoff spec version 0.1.0 in the file where the one in the data/forcefield/ folder has spec 0.2.0.

### CODE REVIEW

**Comment by jchodera** [comment]
Let me push an update to the changelog.

**Comment by jchodera** [comment]
I've updated the changelog with this PR, as well as the other bugfix PRs we've already merged.

**Comment by j-wags** [comment]
I'm concerned that merging this will add another chapter to our already-substantial mutiple-files-with-the-same-name-but-different-contents saga. Could we put off this merge until our versioning questions are resolved? Or is that a longer-term topic?

**Comment by davidlmobley** [comment]
@j-wags seems like it depends on your idea of timescale for resolving the versioning/naming issues. This is a minor fix but should get put in place soon and won't affect anything significantly.

Also, it seems like the files Caitlin noted need to be updated ot the new spec. Should we deal with that in this same PR or do you want to deal with it in a separate PR?

**Comment by jchodera** [comment]
@j-wags: Since we're migrating the smirnoff99Frosst force field to another repo, this PR can be closed and the branch deleted.

**Comment by j-wags** [comment]
Agreed. Closing.

**Pull request closed without merging**
