### PR TITLE
Added an ion_charges.offxml file giving library charges for monatomic ions

### PR DESCRIPTION
**Pull request by dotsdl**
I've added a LibraryCharge entry for each monatomic ion that we currently have vdW params for in openff-1.1.0.xml.

This addresses #305, and is the stage for addressing openforcefield/openforcefield#4, openforcefield/openforcefield#5.

The following now works without obvious error as observed in #305:
```python
from openforcefield.topology import Molecule, Topology
from openforcefield.typing.engines.smirnoff import ForceField

sodium = Molecule.from_smiles('[Na+]')
topology = Topology.from_molecules(sodium)

#force_field_path = get_data_filename('forcefield/smirnoff99Frosst.offxml')
force_field = ForceField('test_forcefields/smirnoff99Frosst.offxml',
                         'test_forcefields/ion_charges.offxml')

system = force_field.create_openmm_system(topology)
```

- [x] Tag issue being addressed
- [x] Add [tests](https://github.com/openforcefield/openforcefield/tree/master/openforcefield/tests)
- [x] Update docstrings/[documentation](https://github.com/openforcefield/openforcefield/tree/master/docs), if applicable
- [x] Update [changelog](https://github.com/openforcefield/openforcefield/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Comment by dotsdl** [comment]
Any ideas on where we should add the following for this change?
- tests
- documentation

**Comment by j-wags** [comment]
Good questions. 
* We should add tests to `test_forcefield`. It could just be one test that loops over all the supported ions using `pytest.mark.parametrize`
* I don't think that this requires a documentation update. Files in `test_forcefields` aren't versioned and should not be used for production work. We'll announce the ion parameters to users with the release in May (since we'll have added these ion parameters to the FF by hand)

**Comment by dotsdl** [comment]
Test added. I also put my name last in the file in the `Authors` tag; I'm not sure what is customary in this project for who is listed in what order.

**Comment by dotsdl** [comment]
This is considered complete and ready for review.

**Comment by dotsdl** [comment]
Merging!

**Pull request merged**
