### PR TITLE
Use m2r2 for markdown doc rendering

### PR DESCRIPTION
**Pull request by dotsdl**
Addresses #598.

I added [m2r2](https://pypi.org/project/m2r2/) as a replacement for `m2r` in our documentation build. Also attempted to fix the table for `<ProperTorsions>` in a nice way, but not sure I'm happy with the result. Trying to make something that works reasonably both rendered and raw in markdown; feedback desired.

- [x] Tag issue being addressed
- [x] Add [tests](https://github.com/openforcefield/openforcefield/tree/master/openforcefield/tests)
- [x] Update docstrings/[documentation](https://github.com/openforcefield/openforcefield/tree/master/docs), if applicable
- [x] Update [changelog](https://github.com/openforcefield/openforcefield/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Comment by j-wags** [comment]
Oh my goodness -- If the `- pip` section in the environment `yml` works, I'm going to cry. I spent a few hours with this before the 0.7.1 release and couldn't figure out how in the world to add a pip dependency to the docs env.

**Comment by j-wags** [comment]
Testing this build here: https://readthedocs.org/projects/open-forcefield-toolkit/builds/11524054/

**Comment by mattwthompson** [comment]
The rendered markdown passes the eye test (in particular https://open-forcefield-toolkit.readthedocs.io/en/doc-fix/smirnoff.html) but I'm not sure what all to look for. There's a TOC on the master build, should that be here, too? https://open-forcefield-toolkit.readthedocs.io/en/master/smirnoff.html

Re: the table, my personal preference would be close to what it was prior, which was probably something similar to the `vdW` section:
image

which looks fine, not perfect, in the raw form

```
| vdW section tag version | Tag attributes and default values                                                                                                                                                                                 | Required parameter attributes                 | Optional parameter attributes |
|-------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------|-------------------------------|
| 0.3                     | `potential="Lennard-Jones-12-6`, `combining_rules="Lorentz-Berthelot"`, `scale12="0"`, `scale13="0"`, `scale14="0.5"`, `scale15="1.0"`, `cutoff="9.0*angstrom"`, `switch_width="1.0*angstrom"`, `method="cutoff"` | `smirks`, `epsilon`, (`sigma` OR `rmin_half`) | `id`, `parent_id`             |
```

I'm not creative enough to think of a way around the verbosity. One concern I have with the changes here is that, at first glance, the rows imply connections between values in adjacent columns that I believe are not intended.

**Comment by j-wags** [comment]
Fixing the `ProperTorsions` section of the spec docs would be nice here, and is worth a merge by itself. 

> Re: the table, my personal preference would be close to what it was prior, which was probably something similar to the vdW section:

I agree with Matt on this. The way that the proposed changes put the ProperTorsion attributes on different rows is a bit rough, and I'd prefer them the same way as we have vdW attributes. I'll approve this PR once that change is made. 

> There's a TOC on the master build, should that be here, too?

The `master` build is ancient... the real bleeding-edge docs are on `latest`. In fact, I'll just go ahead and hide `master` altogether. 

I was hoping that this would recover the API docs from #637, and the links to them from the release notes. But I'm happy to take little bites of this problem to bring back functionality.

**Comment by dotsdl** [comment]
Table reverted to comma-delimited, horizontal format. Building now!

**Comment by dotsdl** [comment]
Okay, this is now consistent with the VDW table @mattwthompson pointed out above; that was a good catch.

**Pull request merged**
