### PR TITLE
Verify toolkit installation

### PR DESCRIPTION
**Pull request by mattwthompson**
Attempt at fixing #664

- [x] Determine how to conditionally uninstall a package (that may or may not be found) without sending a bad exit code
- [x] Tag issue being addressed
- [ ] Add [tests](https://github.com/openforcefield/openforcefield/tree/master/openforcefield/tests)
- [ ] Update docstrings/[documentation](https://github.com/openforcefield/openforcefield/tree/master/docs), if applicable
- [ ] Update [changelog](https://github.com/openforcefield/openforcefield/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Comment by mattwthompson** [comment]
@jaimergp this has me stumped and I could use your help here whenever you had some bandwith. I expected `'RDKit unexpectedly found'` to be caught (see linked issue) but the one-liner isn't even finding OpenEye installed. It shows up in the conda list and nothing fishy has been happening with the license lately, I don't think. Locally, those four one-liners behave as expected (installing/uninstalling each toolkit along the way). It doesn't strike me as an issue with GitHub Actions, conda, or our own software.

**Comment by jaimergp** [comment]
Are we sure is it not due to licensing? This line is oddly suspicious given the expiry date (Jun 2020):

https://github.com/openforcefield/openforcefield/blob/e923cd65152d7dbb91ae3f0e3c2a38bf1874364f/.github/workflows/CI.yml#L94

**Comment by mattwthompson** [comment]
That's probably it - I botched this in #588; the lifetime of that PR extends to before you update the org secret and because that file was changed so much, patch did not get merged in.

**Comment by mattwthompson** [comment]
Okay, that's a relief. Now the failures are only as expected (`RDKit=false, OpenEye=true` because RDKit sneaks in when it maybe should be installed)

**Comment by jaimergp** [comment]
You can `conda remove --force rdkit` in that step condition if needed.

**Comment by mattwthompson** [comment]
I got hung up on how to get that command to behave when the package it's trying to remove might not be there. Not pretty but a bash if does the job

**Comment by mattwthompson** [comment]
Okay, this serves the purpose I intended it to serve. There is probably some golf that could condense it down to fewer characters, but I think it's readable as is.

**Comment by jaimergp** [comment]
LGTM!

**Pull request merged**
