### PR TITLE
Reduce Travis verbosity and remove most LGTM issues

### LINKED ISSUE #234: Reduce test output verbosity
The testing logs in #233 are full of useless output like
```
openforcefield/tests/test_molecule.py::TestMolecule::test_angles[molecule168] PASSED [ 68%]
openforcefield/tests/test_molecule.py::TestMolecule::test_angles[molecule169] PASSED [ 68%]
openforcefield/tests/test_molecule.py::TestMolecule::test_angles[molecule170] PASSED [ 68%]
openforcefield/tests/test_molecule.py::TestMolecule::test_angles[molecule171] PASSED [ 68%]
openforcefield/tests/test_molecule.py::TestMolecule::test_angles[molecule172] PASSED [ 68%]
openforcefield/tests/test_molecule.py::TestMolecule::test_angles[molecule173] PASSED [ 68%]
openforcefield/tests/test_molecule.py::TestMolecule::test_angles[molecule174] PASSED [ 68%]
openforcefield/tests/test_molecule.py::TestMolecule::test_angles[molecule175] PASSED [ 68%]
openforcefield/tests/test_molecule.py::TestMolecule::test_angles[molecule176] PASSED [ 68%]
```
which overruns the Travis console logs. Let's see if we can clean this up at some point.

### PR DESCRIPTION
**Pull request by andrrizzi**
Fix #234 and remove almost all LGTM issues. The remaining LGTM issues are related to `environment.py`, which we're not sure if it will kept around, and `gbsaforces.py`, which I believe is still largely unsupported.

### CODE REVIEW

**Comment by j-wags** [comment]
This pull request **introduces 1 alert** and **fixes 61** when merging a8205cc1cb58fea3936cd1d808bc31f71033a662 into 0b4c5237461eb98f8dd6440f3f75be937cd154b9 - [view on LGTM.com](https://lgtm.com/projects/g/openforcefield/openforcefield/rev/pr-31d4f3e22755218e70f8e26a95428f4f51ab66b3)

**new alerts:**

* 1 for Unused local variable

**fixed alerts:**

* 17 for Unused import
* 13 for Unused local variable
* 11 for Testing equality to None
* 10 for Unreachable code
* 6 for &#39;import \*&#39; may pollute namespace
* 1 for Use of the return value of a procedure
* 1 for Suspicious unused loop iteration variable
* 1 for Module is imported with &#39;import&#39; and &#39;import from&#39;
* 1 for Variable defined multiple times

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by j-wags** [comment]
This pull request **fixes 61 alerts** when merging a3c1ad278b6f07fa51cb47a849c7e1583b2b64a1 into 0b4c5237461eb98f8dd6440f3f75be937cd154b9 - [view on LGTM.com](https://lgtm.com/projects/g/openforcefield/openforcefield/rev/pr-e9d638a560d2c18a4626bec8b8ed2bd14c9ad9e4)

**fixed alerts:**

* 17 for Unused import
* 13 for Unused local variable
* 11 for Testing equality to None
* 10 for Unreachable code
* 6 for &#39;import \*&#39; may pollute namespace
* 1 for Use of the return value of a procedure
* 1 for Suspicious unused loop iteration variable
* 1 for Module is imported with &#39;import&#39; and &#39;import from&#39;
* 1 for Variable defined multiple times

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jchodera** [comment]
Wow, awesome!

**Comment by andrrizzi** [comment]
Thank you!

**Pull request merged**
